<a href="https://colab.research.google.com/github/19pa1a0267/AI-Lab/blob/master/Experiment_No_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
p=np.array([1,2,3])
print(p)

[1 2 3]


1 2) ADD,REMOVE, MODIFY array elements add

In [ ]:
f=np.array([4,8,9])
q=np.append(f,[6,5,8])
print(q)

[4 8 9 6 5 8]


 remove

In [ ]:
c=np.delete(f,2)
print(c)

[4 8]


modify

In [ ]:
c[c>5]=-1
print(c)

[ 4 -1]


 1 3) Arthematic operations on Numpy array

In [ ]:
import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[1.07257442 0.99706981 0.69191418 0.98252712 1.30756781]
 [0.91861243 1.074735   0.98533277 0.38456894 1.67723546]
 [1.30432285 1.60765399 0.69612628 0.68814277 1.14536871]
 [0.85624852 1.8641206  0.52963817 1.26780536 1.06747138]
 [1.23791078 0.94185611 1.17118612 0.9946305  1.62050699]]
[[-0.42752364 -0.48848579 -0.23071804 -0.35995358  0.52926233]
 [ 0.76339395  0.8209582   0.18078122  0.08035324  0.1781254 ]
 [ 0.32985098 -0.37623374  0.0225876  -0.48476453  0.81371372]
 [ 0.2846232  -0.02809191  0.35357034  0.37491787  0.65463185]
 [ 0.47507735  0.57449533  0.43909548  0.64440055 -0.17372563]]
[[0.24190986 0.18888246 0.1063786  0.20894824 0.35740374]
 [0.06526962 0.12027074 0.23454971 0.03535916 0.69534753]
 [0.39811411 0.61074988 0.1210204  0.05963596 0.16243487]
 [0.16303779 0.86853911 0.03887615 0.36669175 0.17773807]
 [0.32668115 0.13926201 0.29471802 0.14350944 0.64896557]]
[[ 0.43000574  0.34235273  0.49986997  0.4637486   2.3600375 ]
 [10.83637964  7.46992313  1.44939623  

1 4)slicing and iterating of numpy array

Slicing

In [ ]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


iterating

In [ ]:
for x in arr:
  print(x)

1
2
3
4
5
6
7


1 5) matrix operations on bumpy arrays

In [ ]:
import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
